<?php
/**
 * Update DTR Records API
 * Saves edited DTR records back to the database
 */

// MUST be first - suppress HTML errors before ANY includes
@ini_set('display_errors', 0);
@ini_set('html_errors', 0);
error_reporting(0);

// Start output buffering BEFORE any includes
ob_start();

// Set JSON header early
header('Content-Type: application/json');

// Custom exception handler
set_exception_handler(function($e) {
    while (ob_get_level() > 0) ob_end_clean();
    echo json_encode([
        'success' => false,
        'message' => 'Exception: ' . $e->getMessage()
    ]);
    exit;
});

// Custom error handler
set_error_handler(function($errno, $errstr, $errfile, $errline) {
    while (ob_get_level() > 0) ob_end_clean();
    echo json_encode([
        'success' => false, 
        'message' => 'PHP Error: ' . $errstr,
        'file' => basename($errfile),
        'line' => $errline
    ]);
    exit;
});

// Now safe to include files
require_once '../config/database.php';
require_once '../config/auth.php';
require_once '../config/csrf.php';

// RE-disable error display AFTER bootstrap overrides (bootstrap may re-enable based on APP_DEBUG)
@ini_set('display_errors', 0);
@ini_set('html_errors', 0);
error_reporting(0);

// Initialize database connection
$pdo = getDBConnection();

// Check authentication (admin only)
if (!isAuthenticated() || !isAdmin()) {
    ob_end_clean();
    echo json_encode(['success' => false, 'message' => 'Unauthorized']);
    exit;
}

// H3: Validate CSRF token
if (!validateCSRFToken()) {
    ob_end_clean();
    echo json_encode(['success' => false, 'message' => 'Invalid CSRF token']);
    exit;
}

// Get JSON input
$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data || !isset($data['employee_id']) || !isset($data['records']) || !is_array($data['records'])) {
    ob_end_clean();
    echo json_encode(['success' => false, 'message' => 'Invalid request data']);
    exit;
}

$employeeId = (int)$data['employee_id'];
$records = $data['records'];
$periodId = isset($data['period_id']) ? (int)$data['period_id'] : 0;

// Get rate fields - STRIP COMMAS before casting to float to handle comma-formatted numbers
// Example: "13,000.00" should become 13000.00, not 13.00
$basicSalary = isset($data['basic_salary']) ? (float)str_replace(',', '', $data['basic_salary']) : null;
$perDay = isset($data['per_day']) ? (float)str_replace(',', '', $data['per_day']) : null;
$otRate = isset($data['ot_rate']) ? (float)str_replace(',', '', $data['ot_rate']) : null;
$lateStart = isset($data['late_start']) ? trim($data['late_start']) : null;
$endTime = isset($data['end_time']) ? trim($data['end_time']) : null;

// Training payment fields
$trainingAmount = isset($data['training_amount']) ? (float)str_replace(',', '', $data['training_amount']) : null;
$trainingRemarks = isset($data['training_remarks']) ? trim($data['training_remarks']) : null;
$dayOverrideMeta = (isset($data['day_override_meta']) && is_array($data['day_override_meta'])) ? $data['day_override_meta'] : null;

if ($employeeId <= 0 || empty($records)) {
    ob_end_clean();
    echo json_encode(['success' => false, 'message' => 'No records to update']);
    exit;
}

try {
    $pdo->beginTransaction();
    
    // When DTR records are updated, remove any cutoff payslips for this employee+period
    // because they are now stale and must be regenerated by the admin.
    if ($periodId > 0) {
        $clearPayslipsStmt = $pdo->prepare("
            DELETE FROM payroll_computations
            WHERE employee_id = ? AND payroll_period_id = ?
              AND other_deductions_notes LIKE '%\"cutoff_type\"%'
        ");
        $clearPayslipsStmt->execute([$employeeId, $periodId]);
    }
    // The basic_monthly_salary in employees table is the base/original salary
    // Any modifications (Sunday pay, bonuses, etc.) are stored only in payroll_computations table
    // This ensures per-day rate calculations always use the correct base salary
    /*if ($basicSalary !== null && $basicSalary > 0) {
        $updateSalaryStmt = $pdo->prepare("UPDATE employees SET basic_monthly_salary = ? WHERE id = ?");
        $updateSalaryStmt->execute([$basicSalary, $employeeId]);
    }*/
    
    // Update payroll computation settings if period_id is provided
        if ($periodId > 0) {
            $stmtComp = $pdo->prepare("
                SELECT id, other_deductions_notes
                FROM payroll_computations
                WHERE payroll_period_id = ? AND employee_id = ?
                LIMIT 1
            ");
            $stmtComp->execute([$periodId, $employeeId]);
            $existingComp = $stmtComp->fetch(PDO::FETCH_ASSOC);

            if ($existingComp) {
                $notes = [];
                if (!empty($existingComp['other_deductions_notes'])) {
                    $decodedNotes = json_decode($existingComp['other_deductions_notes'], true);
                    if (is_array($decodedNotes)) {
                        $notes = $decodedNotes;
                    }
                }

                if (is_array($dayOverrideMeta)) {
                    $notes['day_override'] = $dayOverrideMeta;
                }
                $notes['ot_rate'] = ($otRate !== null && $otRate > 0) ? $otRate : null;

                $otherDeductionsNotes = json_encode($notes);

                $perHour = ($perDay !== null && $perDay > 0) ? ($perDay / 8) : null;
                $perMinute = ($perHour !== null) ? ($perHour / 60) : null;

                $updateCompStmt = $pdo->prepare("
                    UPDATE payroll_computations
                    SET basic_monthly_salary = COALESCE(?, basic_monthly_salary),
                        per_day_rate = COALESCE(?, per_day_rate),
                        per_hour_rate = COALESCE(?, per_hour_rate),
                        per_minute_rate = COALESCE(?, per_minute_rate),
                        late_start = COALESCE(?, late_start, '07:35'),
                        end_time = COALESCE(?, end_time, '17:00'),
                        trainings_cost = COALESCE(?, trainings_cost, 0),
                        training_amount = COALESCE(?, training_amount, 0),
                        training_remarks = COALESCE(?, training_remarks, ''),
                        other_deductions_notes = COALESCE(?, other_deductions_notes),
                        updated_at = NOW()
                    WHERE id = ?
                ");
                $updateCompStmt->execute([
                    $basicSalary,
                    $perDay,
                    $perHour,
                    $perMinute,
                    $lateStart,
                    $endTime,
                    $trainingAmount,
                    $trainingAmount,
                    $trainingRemarks,
                    $otherDeductionsNotes,
                    $existingComp['id']
                ]);
            }
    }
    
    $updateStmt = $pdo->prepare("
        UPDATE dtr_records SET
            am_time_in = :am_in,
            am_time_out = :am_out,
            pm_time_in = :pm_in,
            pm_time_out = :pm_out,
            ot_time_out = :ot_out,
            halfday_in = :half_in,
            halfday_out = :half_out,
            is_halfday = :is_halfday,
            is_absent = :is_absent,
            is_training = :is_training,
            total_work_hours = :work_hrs,
            late_minutes = :late_mins,
            undertime_hours = :ut_hrs,
            daily_ot_hours = :ot_hrs,
            govt_deduct = :govt_deduct,
            remarks = :remarks,
            updated_at = NOW()
        WHERE id = :id AND employee_id = :emp_id
    ");
    
    $updatedCount = 0;
    
    foreach ($records as $rec) {
        if (!isset($rec['id'])) continue;
        
        // Convert empty strings to null for time fields
        $amIn = !empty($rec['am_time_in']) ? $rec['am_time_in'] : null;
        $amOut = !empty($rec['am_time_out']) ? $rec['am_time_out'] : null;
        $pmIn = !empty($rec['pm_time_in']) ? $rec['pm_time_in'] : null;
        $pmOut = !empty($rec['pm_time_out']) ? $rec['pm_time_out'] : null;
        $otOut = !empty($rec['ot_time_out']) ? $rec['ot_time_out'] : null;
        $halfIn = !empty($rec['halfday_in']) ? $rec['halfday_in'] : null;
        $halfOut = !empty($rec['halfday_out']) ? $rec['halfday_out'] : null;
        
        // Use is_halfday from payload (already calculated by frontend based on PM OUT time)
        $isHalfday = isset($rec['is_halfday']) ? (int)$rec['is_halfday'] : 0;
        
        $updateStmt->execute([
            ':id' => (int)$rec['id'],
            ':emp_id' => $employeeId,
            ':am_in' => $amIn,
            ':am_out' => $amOut,
            ':pm_in' => $pmIn,
            ':pm_out' => $pmOut,
            ':ot_out' => $otOut,
            ':half_in' => $halfIn,
            ':half_out' => $halfOut,
            ':is_halfday' => $isHalfday,
            ':is_absent' => isset($rec['is_absent']) ? (int)$rec['is_absent'] : 0,
            ':is_training' => isset($rec['is_training']) ? (int)$rec['is_training'] : 0,
            ':work_hrs' => isset($rec['total_work_hours']) ? (float)$rec['total_work_hours'] : 0,
            ':late_mins' => isset($rec['late_minutes']) ? (int)$rec['late_minutes'] : 0,
            ':ut_hrs' => isset($rec['undertime_hours']) ? (float)$rec['undertime_hours'] : 0,
            ':ot_hrs' => isset($rec['daily_ot_hours']) ? (float)$rec['daily_ot_hours'] : 0,
            ':govt_deduct' => isset($rec['govt_deduct']) ? (float)$rec['govt_deduct'] : 0,
            ':remarks' => isset($rec['remarks']) ? trim($rec['remarks']) : ''
        ]);
        
        $updatedCount += $updateStmt->rowCount();
    }
    
    $pdo->commit();
    
    ob_end_clean();
    echo json_encode([
        'success' => true,
        'message' => "Updated {$updatedCount} record(s) successfully",
        'updated_count' => $updatedCount
    ]);
    
} catch (Exception $e) {
    $pdo->rollBack();
    error_log('DTR Update Error: ' . $e->getMessage());
    ob_end_clean();
    echo json_encode(['success' => false, 'message' => 'Database error: ' . $e->getMessage()]);
}
